[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000
  framework = "next"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/next"
