import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { CartProvider } from "../context/CartContext";
import { ToastProvider } from "../context/ToastContext";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <CartProvider>
            <NavBar />
            {children}
          </CartProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
