[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command   = "npm run dev"
  framework = "next"
  port      = 3000

[[redirects]]
  from   = "/api/*"
  to     = "http://localhost:8000/api/:splat"
  status = 200
